package modul5;

public class Main {

	public static void main(String[] args) {
		Graf lombok909 = new Graf();
		lombok909.addEdge("Sedayu", "Monjok", 9);
        lombok909.addEdge("Sumbawa", "Monjok", 10);
        lombok909.addEdge("Pemenang", "Monjok", 10);
        lombok909.addEdge("Narmada", "Pemenang", 6);
        lombok909.addEdge("Suranadi", "Narmada",  1);
        lombok909.addEdge("Peringgerate", "Narmada", 3);
        lombok909.addEdge("Jempong", "Suranadi", 5);
        lombok909.addEdge("Bima", "Sedayu", 8);
        lombok909.addEdge("Karang Bedil", "Bima", 6);
        lombok909.addEdge("Kekalik", "Karang Bedil", 2);
        lombok909.addEdge("Pagutan", "Kekalik", 7);
        lombok909.addEdge("Sekotong", "Karang Bedil", 10);
        lombok909.addEdge("Sesela", "Karang Bedil", 7);
        lombok909.addEdge("Peraya","Karang Bedil", 4); 
        lombok909.addEdge("Kediri", "Peraya", 1);
        lombok909.addEdge("Gomong", "Bima", 7);
        lombok909.addEdge("Senggigi", "Sesela", 3);   
        lombok909.addEdge("Ampenan", "Gomong", 6);
        lombok909.addEdge("Gerung", "Peraya", 6);
        lombok909.addEdge("Cakra", "Gerung", 2); 
        lombok909.addEdge("Gersik", "Cakra", 10);
        lombok909.addEdge("Mandalika", "Ampenan", 8);
        lombok909.addEdge("Kupang","Mandalika", 10);
        lombok909.addEdge("Gelogor", "Gersik", 2); 
        lombok909.addEdge("Parampuan", "Ampenan", 1);
        lombok909.addEdge("Karang Pule", "Mandalika", 7);
        lombok909.addEdge("Rumak", "Gelogor", 2);   
        lombok909.addEdge("Dasan Cermen", "Karang Pule", 10);
        lombok909.addEdge("Sedayu", "Sumbawa", 1);
        lombok909.addEdge("Sedayu", "Gomong", 3); 
        lombok909.addEdge("Sumbawa", "Pemenang", 6);  
        lombok909.addEdge("Sumbawa", "Bima", 4); 
        lombok909.addEdge("Sumbawa", "Peringgerate", 10); 
        lombok909.addEdge("Pemenang", "Peringgerate", 2);
        lombok909.addEdge("Peringgerate", "Suranadi", 5);
        lombok909.addEdge("Peringgerate", "Kekalik", 7);
        lombok909.addEdge("Jempong", "Peringgerate", 3);
        lombok909.addEdge("Jempong", "Kekalik", 6);
        lombok909.addEdge("Jempong", "Pagutan", 7);
        lombok909.addEdge("Pagutan", "Sekotong", 2);
        lombok909.addEdge("Kekalik", "Sekotong", 5);
        lombok909.addEdge("Karang Bedil", "Kediri", 6);
        lombok909.addEdge("Bima", "Kekalik", 9);
        lombok909.addEdge("Bima", "Kediri", 2);
        lombok909.addEdge("Bima", "Peringgerate", 8);
        lombok909.addEdge("Sesela", "Sekotong", 8);   
        lombok909.addEdge("Sesela", "Peraya", 7);   
        lombok909.addEdge("Kediri", "Gomong", 2);   
        lombok909.addEdge("Kediri", "Gerung", 5);      
        lombok909.addEdge("Gomong", "Gerung", 10);   
        lombok909.addEdge("Peraya", "Senggigi", 10);  
        lombok909.addEdge("Peraya", "Cakra", 10);  
        lombok909.addEdge("Senggigi", "Cakra", 8);
        lombok909.addEdge("Senggigi", "Gersik", 4);
        lombok909.addEdge("Ampenan", "Gerung", 7);   
        lombok909.addEdge("Gerung", "Mandalika", 1);   
        lombok909.addEdge("Gerung", "Kupang", 3);   
        lombok909.addEdge("Cakra", "Rumak", 6);
        lombok909.addEdge("Cakra", "Kupang", 4);
        lombok909.addEdge("Gersik", "Rumak", 1);
        lombok909.addEdge("Rumak", "Dasan Cermen", 5);   
        lombok909.addEdge("Mandalika", "Parampuan", 4); 
        lombok909.addEdge("Parampuan", "Dasan Cermen", 2);  
        lombok909.addEdge("Parampuan", "Karang Pule", 3);  
        lombok909.addEdge("Kupang", "Karang Pule", 10);
        lombok909.addEdge("Karang Pule", "Rumak", 7);
        // lombok909.minimumTraversal("Karang Pule");
		// System.out.println();
		// System.out.println();
		// lombok909.maximumTraversal("Monjok");
		// System.out.println();
		// System.out.println();
        

        Graf lombok910 = new Graf();
        lombok910.addEdge("Sedayu", "Monjok", 7);
        lombok910.addEdge("Sumbawa", "Monjok", 5);
        lombok910.addEdge("Pemenang", "Monjok", 6);
        lombok910.addEdge("Narmada", "Pemenang", 4);
        lombok910.addEdge("Suranadi", "Narmada", 4);
        lombok910.addEdge("Peringgerate", "Narmada", 6);
        lombok910.addEdge("Jempong", "Suranadi", 3);
        lombok910.addEdge("Bima", "Sedayu", 9);
        lombok910.addEdge("Karang Bedil", "Bima", 8);
        lombok910.addEdge("Kekalik", "Karang Bedil", 8);
        lombok910.addEdge("Pagutan", "Kekalik", 2);
        lombok910.addEdge("Sekotong", "Karang Bedil", 4);
        lombok910.addEdge("Sesela", "Karang Bedil", 6);
        lombok910.addEdge("Peraya","Karang Bedil", 10); 
        lombok910.addEdge("Kediri", "Peraya", 3);
        lombok910.addEdge("Gomong", "Bima", 7);
        lombok910.addEdge("Senggigi", "Sesela", 7);   
        lombok910.addEdge("Ampenan", "Gomong", 1);
        lombok910.addEdge("Gerung", "Peraya", 2);
        lombok910.addEdge("Cakra", "Gerung", 1); 
        lombok910.addEdge("Gersik", "Cakra", 10);
        lombok910.addEdge("Mandalika", "Ampenan", 8);
        lombok910.addEdge("Kupang","Mandalika", 3);
        lombok910.addEdge("Gelogor", "Gersik", 9); 
        lombok910.addEdge("Parampuan", "Ampenan", 2);
        lombok910.addEdge("Karang Pule", "Mandalika", 4);
        lombok910.addEdge("Rumak", "Gelogor", 8);   
        lombok910.addEdge("Dasan Cermen", "Karang Pule", 9);
        lombok910.addEdge("Sedayu", "Sumbawa", 8);
        lombok910.addEdge("Sedayu", "Gomong", 4); 
        lombok910.addEdge("Sumbawa", "Pemenang", 7); 
        lombok910.addEdge("Sumbawa", "Bima", 7); 
        lombok910.addEdge("Sumbawa", "Peringgerate", 10); 
        lombok910.addEdge("Pemenang", "Peringgerate", 4);
        lombok910.addEdge("Peringgerate", "Suranadi", 7);
        lombok910.addEdge("Peringgerate", "Kekalik", 4);
        lombok910.addEdge("Jempong", "Peringgerate", 7);
        lombok910.addEdge("Jempong", "Kekalik", 5);
        lombok910.addEdge("Jempong", "Pagutan", 2);
        lombok910.addEdge("Pagutan", "Sekotong", 9);
        lombok910.addEdge("Kekalik", "Sekotong", 10);
        lombok910.addEdge("Karang Bedil", "Kediri", 5);
        lombok910.addEdge("Bima", "Kekalik", 10);
        lombok910.addEdge("Bima", "Kediri", 2);
        lombok910.addEdge("Bima", "Peringgerate", 5);
        lombok910.addEdge("Sesela", "Sekotong", 7);   
        lombok910.addEdge("Sesela", "Peraya", 4);   
        lombok910.addEdge("Kediri", "Gomong", 6);   
        lombok910.addEdge("Kediri", "Gerung", 5);      
        lombok910.addEdge("Gomong", "Gerung", 6);   
        lombok910.addEdge("Peraya", "Senggigi", 5);  
        lombok910.addEdge("Peraya", "Cakra", 6);  
        lombok910.addEdge("Senggigi", "Cakra", 10);
        lombok910.addEdge("Senggigi", "Gersik", 10);
        lombok910.addEdge("Ampenan", "Gerung", 10);   
        lombok910.addEdge("Gerung", "Mandalika", 10);   
        lombok910.addEdge("Gerung", "Kupang", 4);   
        lombok910.addEdge("Cakra", "Rumak", 10);
        lombok910.addEdge("Cakra", "Kupang", 3);
        lombok910.addEdge("Gersik", "Rumak", 9);
        lombok910.addEdge("Rumak", "Dasan Cermen", 4);   
        lombok910.addEdge("Mandalika", "Parampuan", 6); 
        lombok910.addEdge("Parampuan", "Dasan Cermen", 1);  
        lombok910.addEdge("Parampuan", "Karang Pule", 7);  
        lombok910.addEdge("Kupang", "Karang Pule", 7);
        lombok910.addEdge("Karang Pule", "Rumak", 10); 

        lombok910.dijkstra("Karang Pule", "Karang Bedil");
        
        // System.out.println();
        // System.out.println();
        // lombok910.dijkstra("Peraya", "Sekotong");
        // System.out.println();
        // System.out.println();
        // lombok910.dijkstra("Rumak", "Narmada");
        // System.out.println();
        // System.out.println();

        // lombok909.dijkstra("Karang Pule", "Karang Bedil");
        // System.out.println();
        // System.out.println();
        // lombok909.dijkstra("Peraya", "Sekotong");
        // System.out.println();
        // System.out.println();
        // lombok909.dijkstra("Rumak", "Narmada");
        // lombok909.dijkstra("Karang Pule");


        // Graf Kota = new Graf();
        // Kota.addEdge("Sofia", "Enklang", 12);
        // Kota.addEdge("Sofia", "Brahe", 20);
        // Kota.addEdge("Sofia", "Copia", 15);
        // Kota.addEdge("Enklang", "Akaku", 11);
        // Kota.addEdge("Enklang", "Korda", 10);
        // Kota.addEdge("Enklang", "Brahe", 9);
        // Kota.addEdge("Brahe", "Korda", 12);
        // Kota.addEdge("Brahe", "Calle Mort", 12);
        // Kota.addEdge("Brahe", "Lutaros", 11);
        // Kota.addEdge("Brahe", "Copia", 10);
        // Kota.addEdge("Copia", "Lutaros", 8);
        // Kota.addEdge("Lutaros", "Calle Mort", 16);
        // Kota.addEdge("Calle Mort", "Korda", 15);
        // Kota.addEdge("Calle Mort", "Witeka", 20);
        // Kota.addEdge("Korda", "Witeka", 19);
        // Kota.addEdge("Korda", "Lonogo", 12);
        // Kota.addEdge("Akaku", "El Scaro", 8);
        // Kota.addEdge("Akaku", "Lonogo", 16);
        // Kota.addEdge("El Scaro", "Lonogo", 5);
        // Kota.addEdge("Lonogo", "Witeka", 21);
        // Kota.kruskalMST();
        
        // Graf graf = new Graf();
        // graf.addEdge("A", "B", 2);
        // graf.addEdge("A", "C", 3);
        // graf.addEdge("A", "D", 3);
        // graf.addEdge("B", "C", 4);
        // graf.addEdge("B", "E", 3);
        // graf.addEdge("C", "E", 1);
        // graf.addEdge("C", "F", 6);
        // graf.addEdge("D", "F", 7);
        // graf.addEdge("E", "F", 8);
        // graf.addEdge("F", "G", 9);
        
		// graf.primMST("A");
		// graf.minimumTraversal("A");
		// graf.kruskalMST();
		// graf.DFS("A");
		// graf.printGraph();
		// System.out.println(graf.isCyclist());		
	}

}
